version: "3.8"

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_FLASH_ATTENTION=1  
      - OLLAMA_KV_CACHE_TYPE=q8_0
      - GIN_MODE=release
      - OLLAMA_RATE_LIMIT_GENERATE=100
      - OLLAMA_RATE_LIMIT_EMBEDDINGS=50
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    container_name: transcribe_app
    ports:
      - "8000:8000"  # FastAPI app HTTP
    depends_on:
      - ollama
    volumes:
      - ./images:/app/images
      - ./processed_texts:/app/processed_texts
    environment:
      - FORCE_HTTPS=0
#      - APP_URL=http://app:8000  # Ha van egy hasonló beállítás, tedd explicitté
      - OLLAMA_HOST=http://ollama:11434
      - NVIDIA_VISIBLE_DEVICES=all  # GPU láthatóság
      - NVIDIA_DRIVER_CAPABILITIES=all  # GPU funkciók engedélyezése

  ngrok:
    image: ngrok/ngrok
    restart: unless-stopped
    command: "http app:8000  --host-header=app:8000"
    environment:
      - NGROK_AUTHTOKEN=2sTUGqjzViveZPPzqX0duew7Q2V_3yyC1NRojThcUHjqDfvXP
      - NGROK_REGION=eu  # Az ngrok szerver régiójának beállítása
      - NGROK_PROTOCOL=http  # Kényszerített HTTP mód
    ports:
      - "4040:4040"
    depends_on:
      - app

